# © 2022 Numigi (tm) and all its contributors (https://bit.ly/numigiens)
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "product_category_safe_change",
        "product_packaging_dimension_decimal",
        # "onchange_helper",  # Used for testing stock_rental_conversion
        # "stock_dropshipping",  # Used for testing stock_warehouse_access
        # "purchase_warehouse_access",
        "stock_account_visibility",
        # "stock_auto_assign_disabled",
        # "stock_auto_assign_disabled_jit",
        # "stock_client_order_ref",
        # "stock_component",
        # "stock_component_account",
        # "stock_extra_views",
        "stock_immediate_transfer_disable",
        # "stock_inventory_accounting_date_editable",
        # "stock_inventory_category_domain",
        # "stock_inventory_internal_location",
        # "stock_inventory_line_domain",
        # "stock_inventory_line_domain_barcode",
        # "stock_location_position_alphanum",
        # "stock_move_list_cost",
        # "stock_move_list_location",
        "stock_move_location_domain_improved",
        "stock_move_origin_link",
        "stock_picking_secondary_unit_demand",
        # "stock_move_valuation_adjustment",
        # "stock_picking_add_transit",
        # "stock_picking_add_transit_rental",
        # "stock_picking_change_destination",
        # "stock_picking_digitized_signature",
        # "stock_picking_search_by_serial",
        "stock_picking_show_address",
        # "stock_previous_step_return",
        # "stock_product_location_info",
        "stock_product_packaging_dimension",
        "stock_product_packaging_uom",
        "stock_production_lot_rma",
        "stock_quant_secondary_unit",
        # "stock_rental",
        "stock_replenish_report_secondary_unit",
        # "stock_rental_conversion",
        # "stock_rental_conversion_account",
        # "stock_rental_conversion_asset",
        # "stock_reserve_quant_package",
        # "stock_route_optimized",
        # "stock_scheduler_include_rfq",
        # "stock_serial_asset",
        # "stock_serial_no_simple_form",
        # "stock_serial_single_quant",
        # "stock_special_route",
        # "stock_theorical_quantity_access",
        "stock_turnover_rate",
        "stock_turnover_rate_purchase",
        "stock_virtual_adjustment",
        # "stock_warehouse_access",
        # "stock_warehouse_distance",
    ],
    "installable": True,
}
